
language: cpp
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake
      - cmake-data
      - doxygen
      - libudev-dev

install:
  - env
  - if [ "$CC" == "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DBUILD_EXAMPLE_APPLICATIONS=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/INSTALL ..

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make

after_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make doxygen-doc
